from __future__ import annotations

import argparse
import os
import smtplib
from collections.abc import Sequence
from email.message import EmailMessage
from pathlib import Path


def latest_report_path(reports_dir: Path = Path("reports")) -> Path:
    reports = sorted(reports_dir.glob("esi_daily_report_*.pdf"))
    if not reports:
        raise FileNotFoundError(f"No ESI PDF reports found in {reports_dir}")
    return reports[-1]


def latest_diagnostics_report_path(reports_dir: Path = Path("reports/diagnostics")) -> Path:
    reports = sorted(reports_dir.glob("esi_diagnostics_*.pdf"))
    if not reports:
        raise FileNotFoundError(f"No ESI diagnostics PDF reports found in {reports_dir}")
    return reports[-1]


def build_message(
    sender: str,
    recipient: str,
    report_path: Path | None = None,
    report_paths: Sequence[Path] | None = None,
    subject: str | None = None,
) -> EmailMessage:
    paths = [Path(path) for path in (report_paths or ([report_path] if report_path else []))]
    if not paths:
        raise ValueError("At least one report PDF path is required.")
    for path in paths:
        if not path.exists():
            raise FileNotFoundError(f"Report PDF does not exist: {path}")

    message = EmailMessage()
    message["From"] = sender
    message["To"] = recipient
    daily = next((path for path in paths if path.name.startswith("esi_daily_report_")), paths[0])
    message["Subject"] = subject or f"ESI Daily Report - {daily.stem.removeprefix('esi_daily_report_')}"
    message.set_content(
        "Attached are the latest Equity Stress Index (ESI) PDF reports.\n\n"
        "This email was generated by the scheduled GitHub Actions workflow.\n"
    )

    for path in paths:
        with path.open("rb") as handle:
            message.add_attachment(
                handle.read(),
                maintype="application",
                subtype="pdf",
                filename=path.name,
            )
    return message


def send_report(
    sender: str,
    password: str,
    report_path: Path | None = None,
    report_paths: Sequence[Path] | None = None,
    recipient: str | None = None,
    smtp_host: str = "smtp.gmail.com",
    smtp_port: int = 465,
) -> None:
    recipient = recipient or sender
    message = build_message(sender=sender, recipient=recipient, report_path=report_path, report_paths=report_paths)
    with smtplib.SMTP_SSL(smtp_host, smtp_port) as smtp:
        smtp.login(sender, password)
        smtp.send_message(message)


def main() -> None:
    parser = argparse.ArgumentParser(description="Send the latest ESI PDF report by Gmail SMTP.")
    parser.add_argument("--reports-dir", type=Path, default=Path("reports"))
    parser.add_argument("--diagnostics-dir", type=Path, default=Path("reports/diagnostics"))
    parser.add_argument("--report-path", type=Path, default=None)
    parser.add_argument("--diagnostics-report-path", type=Path, default=None)
    parser.add_argument("--include-diagnostics", action="store_true")
    args = parser.parse_args()

    sender = os.environ.get("GMAIL_USERNAME")
    password = os.environ.get("GMAIL_APP_PASSWORD")
    recipient = os.environ.get("REPORT_EMAIL_TO") or sender

    if not sender:
        raise SystemExit("Missing environment variable: GMAIL_USERNAME")
    if not password:
        raise SystemExit("Missing environment variable: GMAIL_APP_PASSWORD")

    report_paths = [args.report_path or latest_report_path(args.reports_dir)]
    if args.include_diagnostics:
        report_paths.append(args.diagnostics_report_path or latest_diagnostics_report_path(args.diagnostics_dir))
    send_report(report_paths=report_paths, sender=sender, password=password, recipient=recipient)
    print(f"Sent ESI report email to {recipient}: {', '.join(str(path) for path in report_paths)}")


if __name__ == "__main__":
    main()
