from __future__ import annotations

import argparse
import os
import smtplib
from email.message import EmailMessage
from pathlib import Path


def latest_report_path(reports_dir: Path = Path("reports")) -> Path:
    reports = sorted(reports_dir.glob("esi_daily_report_*.pdf"))
    if not reports:
        raise FileNotFoundError(f"No ESI PDF reports found in {reports_dir}")
    return reports[-1]


def build_message(
    sender: str,
    recipient: str,
    report_path: Path,
    subject: str | None = None,
) -> EmailMessage:
    report_path = Path(report_path)
    if not report_path.exists():
        raise FileNotFoundError(f"Report PDF does not exist: {report_path}")

    message = EmailMessage()
    message["From"] = sender
    message["To"] = recipient
    message["Subject"] = subject or f"ESI Daily Report - {report_path.stem.removeprefix('esi_daily_report_')}"
    message.set_content(
        "Attached is the latest Equity Stress Index (ESI) daily PDF report.\n\n"
        "This email was generated by the scheduled GitHub Actions workflow.\n"
    )

    with report_path.open("rb") as handle:
        message.add_attachment(
            handle.read(),
            maintype="application",
            subtype="pdf",
            filename=report_path.name,
        )
    return message


def send_report(
    report_path: Path,
    sender: str,
    password: str,
    recipient: str | None = None,
    smtp_host: str = "smtp.gmail.com",
    smtp_port: int = 465,
) -> None:
    recipient = recipient or sender
    message = build_message(sender=sender, recipient=recipient, report_path=report_path)
    with smtplib.SMTP_SSL(smtp_host, smtp_port) as smtp:
        smtp.login(sender, password)
        smtp.send_message(message)


def main() -> None:
    parser = argparse.ArgumentParser(description="Send the latest ESI PDF report by Gmail SMTP.")
    parser.add_argument("--reports-dir", type=Path, default=Path("reports"))
    parser.add_argument("--report-path", type=Path, default=None)
    args = parser.parse_args()

    sender = os.environ.get("GMAIL_USERNAME")
    password = os.environ.get("GMAIL_APP_PASSWORD")
    recipient = os.environ.get("REPORT_EMAIL_TO") or sender

    if not sender:
        raise SystemExit("Missing environment variable: GMAIL_USERNAME")
    if not password:
        raise SystemExit("Missing environment variable: GMAIL_APP_PASSWORD")

    report_path = args.report_path or latest_report_path(args.reports_dir)
    send_report(report_path=report_path, sender=sender, password=password, recipient=recipient)
    print(f"Sent ESI report email to {recipient}: {report_path}")


if __name__ == "__main__":
    main()

